name: New Feature Issue
description: Describe the new feature you are making or enhancing.
title: "[Feature]: "
labels: ["Type: Feature Request"]
projects: ["2024-ThinkingSpace"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following information to allow the team to understand the new feature you are working on.
  - type: textarea
    id: what-feature
    attributes:
      label: What feature are you adding?
      description: Describe the feature you are adding or enhancing and why you are adding it.
      placeholder: Describe the feature you are adding and why.
      value: "This feature... "
    validations:
      required: true
  - type: textarea
    id: feature-requirements
    attributes:
      label: What are the requirements for this feature?
      description: Describe the requirements for this feature.
      placeholder: Describe the requirements for this feature.
      value: "Some requirements: "
    validations:
      required: true
  - type: textarea
    id: feature-implementation
    attributes:
      label: What are the dependencies of this feature?
      description: Describe what is needed to implement this feature. Do you need to add new code, update existing code, add new tests, add or update backend services etc.?
      placeholder: Describe what the dependencies are for this feature.
      value: "This feature needs:"
    validations:
      required: false
  
  - type: dropdown
    id: feature-type
    attributes:
      label: What part of the code does this feature work on
      options:
        - Frontend
        - Backend
        - general
    
  - type: dropdown
    id: feature-priority
    attributes:
      label: What is the priority of this feature?
      options:
        - Low
        - Medium
        - High
